spring.application.name=trust-file-service
spring.datasource.url=jdbc:h2:mem:filedb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jackson.default-property-inclusion=non_null
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
server.port=8092
trust.file.storage.type=local
trust.file.storage.path=${user.home}/trust-file-storage
management.endpoints.web.exposure.include=health,info
