spring:
  application:
    name: trust-gateway-service
  cloud:
    gateway:
      routes:
        - id: quant-trade-service
          uri: http://localhost:8087
          predicates:
            - Path=/quant/**
management:
  endpoints:
    web:
      exposure:
        include: health,info
