spring:
  application:
    name: trust-quant-trade-service
  datasource:
    url: jdbc:h2:mem:quantdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  flyway:
    enabled: true
    locations: classpath:db/migration
  jackson:
    default-property-inclusion: non_null
  cloud:
    kubernetes:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  paths-to-match: /quant/**
  swagger-ui:
    path: /swagger-ui.html

trust:
  quant:
    max-notional: 1000000
    mock-market-enabled: true
    account-service:
      url: http://localhost:8091

server:
  port: 8087
