spring.application.name=trust-quant-trade-service
spring.datasource.url=jdbc:h2:mem:quantdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.jackson.default-property-inclusion=non_null
spring.cloud.kubernetes.enabled=false
management.endpoints.web.exposure.include=health,info
springdoc.paths-to-match=/quant/**
springdoc.swagger-ui.path=/swagger-ui.html
trust.quant.max-notional=1000000
trust.quant.mock-market-enabled=true
trust.quant.account-service.url=http://localhost:8091
server.port=8087
